import {
    Box,
    Center,
    Flex,
    Heading,
    HStack,
    Input,
    Text,
    useRadioGroup,
    VStack,
} from '@chakra-ui/react';
import { throws } from 'assert';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState } from 'react';
import RegionRadioButton from '../components/RegionRadioButton';
import fetcher from '../lib/fetcher';

export default function Home() {
    const [region, setRegion] = useState('EUW');
    const [name, setName] = useState('LKDixon');
    const [data, setData] = useState({});
    const router = useRouter();

    async function handleSubmit(event) {
        event.preventDefault();
        router.push(`/profile/${region}/${name}`);
    }

    return (
        <Box height="100%">
            <Head>
                <title>DIXON GG: The Best League of Legends Stat Tracker</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex as="main" height="100%">
                <Center
                    width="100%"
                    alignItems="center"
                    justifyContent="center"
                >
                    <VStack>
                        <Heading as="h1">Dixon.gg</Heading>
                        <Text>{name}</Text>
                        <form onSubmit={handleSubmit}>
                            <Input
                                type="text"
                                placeholder="Search Yourself or a Champion"
                                onChange={(e) => setName(e.target.value)}
                            ></Input>
                            {Example()}
                        </form>
                    </VStack>
                </Center>
            </Flex>
        </Box>
    );

    function Example() {
        const options = [
            'NA',
            'EUW',
            'EUN',
            'KR',
            'BR',
            'JP',
            'RU',
            'OCE',
            'TR',
            'LAN',
            'LAS',
        ];

        const { getRootProps, getRadioProps } = useRadioGroup({
            name: 'region',
            defaultValue: 'EUW',
            onChange: (value) => setRegion(value),
        });

        const group = getRootProps();

        return (
            <HStack {...group}>
                {options.map((value) => {
                    const radio = getRadioProps({ value });
                    return (
                        <RegionRadioButton key={value} {...radio}>
                            {value}
                        </RegionRadioButton>
                    );
                })}
            </HStack>
        );
    }
}
